language: python
python:
  - "3.5"

install:
  - pip install .
  - pip install coveralls

script:
  - nosetests --verbose --with-coverage --cover-package=sw_excel_parser

after_success:
  - coveralls
