language: python
python:
  - "3.5"

install:
  - pip install .
  - pip install coverage coveralls nose

script:
  - nosetests -v --with-coverage --cover-package=sw_excel_parser

after_success:
  - coveralls
